name: Build and Archive
on:
  push:
    branches: [ master ]
    paths:
      - 'Hyperlink.xcodeproj/**'
      - 'Hyperlink/**'
  pull_request:
    branches: [ master ]
    paths:
      - 'Hyperlink.xcodeproj/**'
      - 'Hyperlink/**'
jobs:
  build:
    runs-on: macos-14
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Xcode
        run: sudo xcode-select -s /Applications/Xcode_16.2.app
      
      - name: Build and Archive
        run: |
          xcodebuild -version
          xcodebuild clean archive \
            -project Hyperlink.xcodeproj \
            -scheme "Hyperlink" \
            -configuration Release \
            -archivePath ${{ github.workspace }}/build/Hyperlink.xcarchive \
            CODE_SIGN_IDENTITY=- \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO
